config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :tools do
    resources :rentals, only: %i[new create]
  end
  resources :rentals, only: %i[show edit update destroy]
  get "my_tools", to: "tools#my_tools"
  get "my_rentals", to: "rentals#my_rentals"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :tool

  before_save :calculate_cost

  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date

  def num_days
    self.days = (end_date.to_i - start_date.to_i) / 86_400
  end

  def calculate_cost
    self.cost = tool.price * (end_date.to_i - start_date.to_i) / 86_400
  end

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end
end

app/models/tool.rb
class Tool < ApplicationRecord
  include PgSearch::Model

  belongs_to :user

  has_many :rentals, dependent: :destroy
  has_many_attached :photos

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }

  pg_search_scope :search_by_name_and_address,
    against: [ :name, :address ],
    ignoring: :accents,
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :tools, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :address, :phone, :avatar])
  end

  def after_sign_in_path_for(user)
    tools_url(user)
  end

  def after_sign_out_path_for(user)
    tools_url(user)
  end

  def user_root_path
    tools_url(@user)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rented_tool, only: %i[new create]

  def new
    @rental = Rental.new
    authorize @rental
  end

  def create
    @rental = Rental.new(rental_params)
    @rental.user = current_user
    @rental.tool = @tool
    authorize @rental
    if @rental.save
      @tool.update(available: false)
      redirect_to my_rentals_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    authorize @rental
  end

  def my_rentals
    @rentals = Rental.where(user: current_user)
    authorize @rentals
  end

  private

  def rental_params
    params.require(:rental).permit(:days, :delivery, :start_date, :end_date)
  end

  def set_rented_tool
    @tool = Tool.find(params[:tool_id])
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_tool, only: %i[show edit update destroy]

  def index
    if params[:query].present?
      @tools = policy_scope(Tool).search_by_name_and_address(params[:query])
    else
      @tools = policy_scope(Tool)
    end
    @markers = @tools.geocoded.map do |tool|
      {
        lat: tool.latitude,
        lng: tool.longitude,
        info_window: render_to_string(partial: "info_window", locals: { tool: tool })
      }
    end
  end

  def my_tools
    @tools = Tool.where(user: current_user)
    authorize @tools
  end

  def new
    @tool = Tool.new
    authorize @tool
  end

  def create
    @tool = Tool.new(tool_params)
    @tool.user = current_user
    @tool.address = current_user.address
    authorize @tool
    if @tool.save
      redirect_to my_tools_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    authorize @tool
  end

  def edit
    authorize @tool
  end

  def update
    authorize @tool
    if tool_params[:photos].length > 1
      if @tool.update(tool_params)
        redirect_to tool_path(@tool)
      else
        render :edit
      end
    else
      if @tool.update(tool_params.except(:photos))
        redirect_to tool_path(@tool)
      else
        render :edit
      end
    end
  end

  def destroy
    authorize @tool
    @tool.destroy
    # No need for app/views/tools/destroy.html.erb
    redirect_to my_tools_path, status: :see_other
  end

  private

  def set_tool
    @tool = Tool.find(params[:id])
  end

  def tool_params
    params.require(:tool).permit(:name, :price, :user, :address, :available, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tool Handler</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta property='og:title' content='Tool Handler'/>
    <meta property='og:image' content='https://res.cloudinary.com/djlk9ksfg/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1667857093/Tool_Handle_Landing_g5kzqy.jpg'/>
    <meta property='og:description' content="Don't buy tools for single-use, rent them!"/>
    <meta property='og:url' content='https://tool-handler.herokuapp.com/'/>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>


    <script src='https://api.mapbox.com/mapbox-gl-js/v2.10.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.10.0/mapbox-gl.css' rel='stylesheet' />


    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="d-flex justify-content-around mt-4">

    <div class="landing-main-card">
      <%= image_tag("card1.png", width: 300, height: 600, crop: :scale) %>
      <h2 class="landing-text text-1">Need a tool?</h2>
    </div>

    <div class="landing-main-card">
      <div>
        <%= image_tag("card2.png", width: 300, height: 500, crop: :scale) %>
        <h2 class="landing-text text-2">Tool Handler can help you!</h2>
      </div>
      <div>
        <%= link_to "START NOW!", tools_path, class:"home btn-yellow-lg shadow" %>
      </div>
    </div>

    <div class="ps-5 landing-main-card">
      <%= image_tag("card3.png", width: 300, height: 600, crop: :fit) %>
      <h2 class="landing-text text-3">Rent the tool you need in here!</h2>
    </div>

  </div>

</div>

app/views/rentals/my_rentals.html.erb
<div class="container">
  <h1 class="my-3">My Rentals</h1>

  <% @rentals.each do |rental| %>
    <% if rental.user == current_user %>

      <div class="card-product mb-4">


        <% if rental.tool.photos.attached? %>
            <img src="<%= cl_image_path rental.tool.photos[0].key, height: 300, width: 400, crop: :pad %>">
        <% else %>
          <img src="https://source.unsplash.com/random/300×700/?<%= rental.tool.name.gsub(" ","-")%>)">
        <% end %>

        <div class="card-product-infos ms-3">
          <h2 class="mb-4"><%= rental.tool.name.capitalize %></h2>
          <p>You rented it for: <strong><%= rental.num_days %></strong> days (to be returned by <%= rental.end_date.strftime("%B %-d, %Y") %>)</p>
          <p>Price per day: <strong><%= number_to_currency(rental.tool.price) %></strong></p>
          <p>Final price: <strong><%= number_to_currency(rental.tool.price * rental.num_days) %></strong></p>
        </div>
      </div>



    <% end %>
  <%end%>
      <span class="mb-2"><%= link_to :back do %>
          <i class="fa-solid fa-arrow-left" style="font-size: 30px; color: orange"></i>
        <% end %>
      </span>
</div>

app/views/rentals/new.html.erb
<div class="container" data-controller="hello">
  <h1 class="mt-3">Rent <%= @tool.name %></h1>
  <div class="d-flex justify-content-center">
    <% if Rental.find_by(tool_id: @tool.id).present? %>
      <h4 class="mt-4" style="color: red">Sorry, this tool is currently rented!</h5>
    <% else %>
      <div  class="center-form shadow">
        <%= simple_form_for [@tool, @rental] do |f| %>
          <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
          <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
          <%= f.input :delivery, collection: [ "Pickup", "Delivery"], label: "Chose delivery method:" %>
          <%= f.submit "Rent", :class => "btn-yellow-lg" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to tools_path, class: "navbar-brand" do %>
      <%= image_tag "ferramenta.png"  %>
      <h1>TOOL HANDLER</h1>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", tools_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My tools", my_tools_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My rentals", my_rentals_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <% if current_user.avatar.attached? %>
            <%= cl_image_tag current_user.avatar.key, transformation: [{gravity: "face", height: 400, width: 400, crop: "thumb"}], class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
             <a class="nav-link" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa-regular fa-user"></i>
            </a>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit my profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tools/_info_window.html.erb
<h5><%= tool.name.capitalize %></h5>
<p><%= tool.address %></p>
<p><%= number_to_currency(tool.price) %></p>

app/views/tools/edit.html.erb
<div class="container">
  <div class="d-flex justify-content-center">
    <div  class="center-form shadow">
      <%= simple_form_for @tool do |f| %>
        <%= f.input :name, label: "Edit the tool's name:" %>
        <%= f.input :price %>
        <%= f.input :photos, as: :file , input_html: { multiple: true }, required: false, class:"mb-2",
          hint: "You can leave this blank if you're not updating the photo" %>
        <%= f.input :available %>
        <%= f.submit "Update", :class => "btn-yellow-lg" %>
      <% end %>
    </div>
  </div>
  <span class="mb-2"><%= link_to :back do %>
          <i class="fa-solid fa-arrow-left" style="font-size: 30px; color: orange"></i>
        <% end %>
      </span>
</div>

app/views/tools/index.html.erb
<div class="container">
  <div class="index-main-container mt-3">
    <div>
      <div>
        <%= form_with url: tools_path, method: :get, class: "d-flex mt-1 mb-3" do %>
          <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Find a tool" %>
                <%= submit_tag "Search", class: "btn btn-black-sm" %>
        <% end %>
        <h1>TOOLS FOR RENT</h1>
        <p style="margin-left:auto; margin-righ:auto;">Tools for Rent Near You!</p>
      </div>
      <div class="filter-form align-items-center">
        <%= link_to "Add New Tool", new_tool_path, class:"btn-yellow-lg add-tool-index" %>
      </div>
      <div data-controller="map"
        id='map'
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
    <div class="tools-grid">
      <% @tools.each do |tool| %>
        <div class="card card-index">
          <% if tool.photos.attached? %>
            <img class="card-img-top card-img-top-index cover" src="<%= cl_image_path tool.photos[0].key, height: 300, width: 400, crop: :pad %>">
          <% else %>
            <img class="card-img-top card-img-top-index cover" src="https://source.unsplash.com/random/300×150/?<%= tool.name.gsub(" ","-")%>)">
          <% end %>

          <% if tool.available %>
            <h6 class="card-title text-center fw-semibold p-1"><%= tool.name.capitalize %>
          <% else %>
            <h6 class="card-title text-center fw-semibold p-1 text-muted"><%= tool.name.capitalize %>
            <p class="text-muted small">(Rented)</p>
          <% end %>
          <div class="d-fex">
            <span class="position-absolute bottom-0 start-0 m-1 ms-2 p-1"><%= number_to_currency(tool.price)%></span>
            <%= link_to "See Details", tool_path(tool), class:"btn-yellow position-absolute bottom-0 end-0" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tools/my_tools.html.erb
<div class="container">
  <div class="d-flex">
    <div class="mt-3">
      <h1>My Tools</h1>
      <p>Hello, <%= current_user.name %>! Here are the tools you put up for rent: </p>
    </div>
    <div class="filter-form align-items-center">
      <%= link_to "Add New Tool", new_tool_path, class:"btn-yellow-lg end-0", id:"my-add" %>
    </div>
  </div>


  <div class="tools-grid-my-tools">

    <% @tools.each do |tool| %>
      <div class="card card-index">
        <% if tool.photos.attached? %>
          <img class="card-img-top card-img-top-index cover" src="<%= cl_image_path tool.photos[0].key, height: 300, width: 400, crop: :pad %>">
        <% else %>
          <img class="card-img-top card-img-top-index cover" src="https://source.unsplash.com/random/300×150/?<%= tool.name.gsub(" ","-")%>)">
        <% end %>
        <h6 class="card-title text-center fw-semibold p-1"><%= tool.name.capitalize %></h6>
        <div class="d-fex">
          <span class="position-absolute bottom-0 start-0 m-1 ms-2 p-1"><%= number_to_currency(tool.price)%></span>
          <%= link_to "See Details", tool_path(tool), class:"btn-yellow position-absolute bottom-0 end-0" %>
        </div>
      </div>
    <% end %>
  </div>
<span class="mb-2"><%= link_to :back do %>
          <i class="fa-solid fa-arrow-left  mt-5" style="font-size: 30px; color: orange"></i>
        <% end %>
      </span>
</div>

app/views/tools/new.html.erb
<div class="container">
  <div class="d-flex justify-content-center">
    <div  class="center-form shadow">
      <%= simple_form_for @tool do |f| %>
        <%= f.input :name, label: "Enter new tool's name:" %>
        <%= f.input :price %>
        <%# f.input :address,
          input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
          wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
        %>
        <%= f.input :photos, as: :file, input_html: { multiple: true }, class:"mb-2" %>
        <%= f.submit "Add new tool", :class => "btn-yellow-lg" %>
      <% end %>
    </div>
  </div>
  <span class="mb-2"><%= link_to :back do %>
          <i class="fa-solid fa-arrow-left mt-5" style="font-size: 30px; color: orange"></i>
        <% end %>
      </span>
</div>

app/views/tools/show.html.erb
<div class="container">
  <div class="ms-4 mb-4 mt-2">
    <h1><%= @tool.name.capitalize %></h1>
  </div>


  <div class="row">


    <div class="col-2">
      <ul style="list-style: none;">

        <% if @tool.photos.attached? %>

          <% @tool.photos.each_with_index do |photo, index| %>
            <li class="show-carousel-img mb-2"><%= cl_image_tag photo.key, height: 120, width: 120, crop: :pad %></li>
          <% end %>

        <% else %>
          <li><img class="show-carousel-img mb-1" src="https://source.unsplash.com/random/120×120/?<%= @tool.name.gsub(" ","-")%>)"></li>
          <li><img class="show-carousel-img mb-1" src="https://source.unsplash.com/random/120×120/?<%= @tool.name.gsub(" ","-")%>)"></li>
          <li><img class="show-carousel-img mb-1" src="https://source.unsplash.com/random/120×120/?<%= @tool.name.gsub(" ","-")%>)"></li>
          <li><img class="show-carousel-img mb-1" src="https://source.unsplash.com/random/120×120/?<%= @tool.name.gsub(" ","-")%>)"></li>
        <% end %>

      </ul>
    </div>
    <div class="col-6 d-flex justify-content-center">
      <% if @tool.photos.attached? %>
          <img class="img-fluid show-img" src="<%= cl_image_path @tool.photos[0].key, crop: :pad %>">
        <% else %>
          <img class="img-fluid show-img" src="https://source.unsplash.com/random/400×400/?<%= @tool.name.gsub(" ","-")%>)">
        <% end %>
    </div>
    <div class="col-3 bg-dark text-white h-75 d-inline-block pt-2">
      <p>
        <% if @tool.rating.present? %>
          <% @tool.rating.times do %>
            <i class="fa-solid fa-star" style="color: #FEDE01;"></i>
          <%end%>
          <% (5 - @tool.rating).times do %>
            <i class="fa-regular fa-star" style="color: #FEDE01;"></i>
          <%end%>
        <%else%>
          <% 5.times do %>
            <i class="fa-regular fa-star" style="color: #FEDE01;"></i>
          <%end%>
        <%end%>
      </p>
      <div class="mb-3">
      <span>Offered by: <%= @tool.user.name %> </span>
      </div>
      <div class="price fs-2 mb-3">
        <%= number_to_currency(@tool.price) %>
      </div>
      <div class="mb-4">
        <% if @tool.user == current_user %>
          <div class = "d-flex justify-content-around">
            <%= link_to "Edit tool", edit_tool_path(@tool), class:"btn-orange-lg" %>
            <%= link_to "Delete",
              tool_path(@tool),
              data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, :class => "btn-yellow-lg"
            %>
          </div>
        <% elsif Rental.find_by(tool_id: @tool.id).present? %>
          <h5 style="color: red">Rented until <%= Rental.find_by(tool_id: @tool.id).end_date.strftime("%B %-d, %Y") %></h5>
         <% elsif !@tool.available %>
          <h5 style="color: red">Unavailable</h5>
        <% else %>
          <%= link_to "Rent now", new_tool_rental_path(@tool), class:"btn-yellow-lg" %>
        <% end %>
      </div>
    </div>
  </div>